name: Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Gitea Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Create Release
        uses: https://gitea.com/gitea-actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: true
          draft: false
          prerelease: false
